[project]
name = "rag-tokenizer"
version = "0.0.2"
requires-python = ">=3.10,<3.15"
dependencies = [
    "readerwriterlock>=1.0.0,<2.0.0",
    "datrie>=0.8.3,<0.9.0",
    "hanziconv>=0.3.0,<0.4.0",
    "nltk>=3.9.0,<4.0.0"
]
description = "Rag tokenizer for RAGFlow"
readme = "README.md"