[general]
version                  = "0.4.0"
time_zone                = "utc-8"
server_mode              = "standalone"

[network]
server_address           = "0.0.0.0"

[log]
log_filename             = "infinity.log"
log_dir                  = "/var/infinity/log"
log_to_stdout            = true
log_level               = "trace"

[storage]
persistence_dir          = "/var/infinity/persistence"

storage_type             = "minio"

[storage.object_storage]
url                      = "127.0.0.1:9000"
bucket_name              = "infinity"
access_key               = "minioadmin"
secret_key               = "minioadmin"
enable_https             = false

[buffer]
buffer_manager_size      = "8GB"
temp_dir                 = "/var/infinity/tmp"

[wal]
wal_dir                  = "/var/infinity/wal"

[resource]
resource_dir             = "/var/infinity/resource"